volumes:
  data:

services:
  postgres:
    image: postgres:14.7
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: financial
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
