authentication:
  enabled: true

server:
  port: 8484
  servlet:
    context-path: /api
spring:
  application:
    name: financial-control
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-quiet-paper-a2x9rzsf-pooler.eu-central-1.aws.neon.tech/financial
    username: neondb_owner
    password: npg_vJmqn82jtNDw
logging:
  level:
    app.core: debug
