name: CI pipeline

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: building application
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4 #

      - name: setup java and maven
        uses: actions/setup-java@v3 
        with:
           java-version: '21'
           distribution: 'temurin'

      - name: setup docker
        uses: docker/setup-buildx-action@v3

      - name: start up app and database
        run: 
          docker compose -f docker-compose.yaml up -d

      - name: run liquibase migrations dry-run
        run: |
          cd migration
          mvn -Plocal liquibase:update

      # - name: upload artifact
      #   uses: actions/upload-artifact@v4.6.2
      #   with:
      #     name: financial-controll-app
      #     path: /core/target
  
  # ci-deploy:
  #   name: deploy on render ci environment
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.event_name != 'workflow_dispatch'
  #   steps:
  #     - name: download artifact
  #       uses: actions/download-artifact@v4.3.0
  #       with:
  #         name: financial-controll-app
  #     - name: deploy to render.com
