name: CI pipeline

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: building application
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:15
    #     env:
    #       POSTGRES_DB: financial
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: 1234
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4 #

      - name: setup java and maven
        uses: actions/setup-java@v3 
        with:
           java-version: '21'
           distribution: 'temurin'

      - name: setup docker
        uses: docker/setup-buildx-action@v3
          
      - name: build with maven
        run: mvn clean package 

      - name: start up database
        run: | 
          cd migration
          docker compose -f doker-compose.yaml up

      - name: run liquibase migrations
        run: |
          cd migration
          mvn -Plocal liquibase:update

      # - name: liquibase migration update dry-run
      #   uses: liquibase-github-actions/update@v4.32.0
      #   env:
      #     JAVA_HOME: ${{ env.JAVA_HOME }}
      #   with:
      #     changelogFile: migration/src/main/resources/db/master.xml
      #     url: "jdbc:postgresql://postgres:5432/financial"
      #     password: "1234"
      #     showSummary: "verbose"
      #     showSummaryOutput: "all"
      #     username: "postgres"
